# linux
# requirements: libsdl2-dev libsdl2-image-dev

# compiler & Flags
cxx = g++
cxxflags = -Wall -I"include/sdl2" -I"include/headers"

# libs
libpath = -L"lib"
libs = -lSDL2 -lSDL2_image

# src & output
src = $(wildcard src/*.cpp) $(wildcard src/*/*.cpp)
output = build/8964

all: $(output)

$(output): $(src)
	$(cxx) $(cxxflags) $(libpath) -o $@ $^ $(libs)

clean:
	rm -f $(output)
