# compiler & flags
cxx = g++
cxxflags = -Wall -I"include" -I"include/sdl2" -I"include/headers"

# libs
libpath = -L"lib"
libs = -l"mingw32" -l"SDL2main" -l"SDL2" -l"SDL2_image" -l"z"

# src & output
src = $(wildcard src/*.cpp) $(wildcard src/*/*.cpp)
output = build/8964.exe

all: $(output)

$(output): $(src)
	$(cxx) $(cxxflags) $(libpath) -o $@ $^ $(libs)

clean:
	del $(output)

# https://stackoverflow.com/questions/64396979/how-do-i-use-sdl2-in-my-programs-correctly